apiVersion: dapr.io/v1alpha1
kind: Subscription
metadata:
  name: simulator_subscription
spec:
  topic: test   
  route: /test
  pubsubname: simulatorpubsub
#These services subscibe to the topic "test"
scopes:
  - service-b
  - service-c

