apiVersion: dapr.io/v1alpha1
kind: Subscription
metadata:
  name: dependent_subscription
spec:
  topic: dependent_topic   
  route: /dependent_topic
  pubsubname: simulatorpubsub
#These services subscibe to the topic "dependent_topic"
scopes:
  - service-b