apiVersion: dapr.io/v1alpha1
kind: Subscription
metadata:
  name: dependent_subscription3
spec:
  topic: topic4   
  route: /topic4
  pubsubname: simulatorpubsub
#These services subscribe to the topic "topic4"
scopes:
  - service-a