apiVersion: dapr.io/v1alpha1
kind: Subscription
metadata:
  name: dependent_subscription4
spec:
  topic: delayed_topic
  route: /delayed_topic
  pubsubname: simulatorpubsub
#These services subscribe to the topic "topic3"
scopes:
  - service-b