version : '3'
networks:
  default:
    external:
      name: my-dapr-network

services:
  ############################
  # servicetwo app + Dapr sidecar
  ############################
  servicetwoapp:
    image: servicetwoapp
    build:
      context: .
      dockerfile: .
    ports:
      - "3500:3500" # HOST_PORT:CONTAINER_PORT

  servicetwoapp-dapr:
    image: "daprio/daprd:edge"
    command: ["./daprd",
              "-app-id", "servicetwoapp",
              "--dapr-http-port", "3500",
              "-app-port", "8080", # Same as Expose port of Dockerfile of the respective service
              "-components-path", "/components",
              "-log-level", "debug"]
    volumes:
      - "./components/:/components"
    depends_on:
      - servicetwoapp
    network_mode: "service:servicetwoapp"


