# Generated by Django 3.2 on 2021-05-04 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='district_id',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
    ]
