# Generated by Django 3.2 on 2021-05-08 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0002_location_district_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Location',
        ),
    ]
