version: '3'
networks:
  microservices_nw:
    external: true
services:
  ############################
  # serviceone + Dapr sidecar
  ############################
  servicea:
    build: ./serviceA
    ports:
      - "3500:3500"
    expose:
      - 3500
    depends_on:
      - zipkin
      - redis
      - placement
    networks:
      - microservices_nw

      ############################
      # serviceone Dapr sidecar
      ############################
  servicea-dapr:
    image: "daprio/daprd:edge"
    command: ["./daprd",
              "-app-id", "service-a",
              "--dapr-http-port", "3500",
              "-app-port", "8090",
              "-placement-host-address", "placement:50006",
              "--components-path", "./components",
              "--config","/components/observability.yaml",
              "-dapr-grpc-port", "50002"]

    volumes:
      - "./components/:/components"
    depends_on:
      - servicea
    network_mode: "service:servicea"
  ############################
  # servicetwo + Dapr sidecar
  ############################
  serviceb:
    build: ./ServiceB
    ports:
      - "3501:3501"
    expose:
      - 3501
    depends_on:
      - zipkin
      - redis
      - placement
    networks:
      - microservices_nw
    
    
      #####################
      # servicetwo Dapr sidecar
      ############################
  serviceb-dapr:
    image: "daprio/daprd:edge"
    command: ["./daprd",
              "-app-id", "service-b",
              "--dapr-http-port", "3501",
              "-app-port", "8080",
              "-placement-host-address", "placement:50006",
              "--components-path", "./components",
              "--config","/components/observability.yaml",
              "-dapr-grpc-port", "50002"]

    volumes:
      - "./components/:/components"
    depends_on:
      - serviceb
    network_mode: "service:serviceb"
  ############################
  # Dapr placement service
  ############################
  placement:
    image: "daprio/dapr"
    command: ["./placement", "-port", "50006"]
    ports:
      - "50006:50006"
    networks:
      - microservices_nw
  
  ############################
  # servicethree + Dapr sidecar
  ############################
  servicec:
    build: ./ServiceC
    ports:
      - "3502:3502"
    expose:
      - 3502
    depends_on:
      - zipkin
      - redis
      - placement
    networks:
      - microservices_nw
  
      #####################
      # servicethree Dapr sidecar
      ############################
  servicec-dapr:
    image: "daprio/daprd:edge"
    command: ["./daprd",
              "-app-id", "service-c",
              "--dapr-http-port", "3502",
              "-app-port", "8091",
              "-placement-host-address", "placement:50006",
              "--components-path", "./components",
              "--config","/components/observability.yaml",
              "-dapr-grpc-port", "50002"]

    volumes:
      - "./components/:/components"
    depends_on:
      - servicec
    network_mode: "service:servicec"
  
  ############################
  # Redis state store
  ############################
  redis:
    image: "redis"
    ports:
      - "6379:6379"
    expose:
      - 6379
    networks:
      - microservices_nw

  ############################
  # Zipkin
  ############################
  zipkin:
    image: "openzipkin/zipkin"
    ports:
      - "9411:9411"
    expose:
      - 9411
    networks:
      - microservices_nw